name: Build & Test SAGE OS on Multi-Architecture

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.architecture }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, arm64, aarch64, riscv64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ make
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-x86-64-linux-gnu gcc-riscv64-linux-gnu
          sudo apt-get install -y qemu-system-x86 qemu-system-arm qemu-system-misc

      - name: Build kernel
        run: |
          make clean
          make ARCH=${{ matrix.architecture }}
          
          # Check if build artifacts were created
          if [ ! -f "kernel.elf" ] || [ ! -f "kernel8.img" ]; then
            echo "Error: Build failed to produce kernel artifacts for ${{ matrix.architecture }}"
            exit 1
          fi
          
          # Create build directory and copy artifacts
          mkdir -p build/${{ matrix.architecture }}
          cp kernel.elf build/${{ matrix.architecture }}/
          cp kernel8.img build/${{ matrix.architecture }}/kernel.img
          
          # Copy kernel8.img for ARM architectures
          if [[ "${{ matrix.architecture }}" == "arm64" || "${{ matrix.architecture }}" == "aarch64" ]]; then
            cp kernel8.img build/${{ matrix.architecture }}/
          fi
          
          # List build artifacts for debugging
          echo "Build artifacts:"
          find build -type f | sort

      - name: Test kernel
        run: |
          chmod +x scripts/test_emulated.sh
          
          # List build artifacts for debugging
          echo "Build artifacts before testing:"
          find build -type f | sort
          
          # Run the test
          echo "Testing ${{ matrix.architecture }} build with QEMU..."
          timeout 30s scripts/test_emulated.sh ${{ matrix.architecture }} || true

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: sageos-${{ matrix.architecture }}
          path: build/${{ matrix.architecture }}/
