name: Build Test

on:
  push:
    branches: [ main, origin, rpi5-os-implementation ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu qemu-system-arm
      
      - name: Build kernel
        run: |
          make clean
          make ARCH=aarch64
          
          # Check if build artifacts were created
          if [ ! -f "build/aarch64/kernel.elf" ] || [ ! -f "build/aarch64/kernel.img" ]; then
            echo "Error: Build failed to produce kernel artifacts"
            exit 1
          fi
          
          echo "✅ Build successful"
      
      - name: Test with QEMU
        run: |
          # Run the emulation test script
          ./scripts/test_emulated.sh aarch64 5
          echo "QEMU test completed"