name: License Headers

on:
  push:
    branches: [ main, origin, rpi5-os-implementation ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, origin ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  add-license-headers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Check for missing license headers
        id: check-headers
        continue-on-error: true
        run: |
          if python enhanced_license_headers.py --check-only --verbose; then
            echo "All files have license headers"
            echo "missing_headers=false" >> $GITHUB_OUTPUT
          else
            echo "Missing license headers detected"
            echo "missing_headers=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Add license headers if missing
        if: steps.check-headers.outputs.missing_headers == 'true'
        run: |
          # Add license headers to files
          python enhanced_license_headers.py --verbose --stats
          
          # Configure git
          git config --global user.name "SAGE OS Bot"
          git config --global user.email "sage-os-bot@example.com"
          
          # Check if there are changes to commit
          if [[ -n $(git status -s) ]]; then
            # Stage all changes
            git add .
            
            # Get the list of modified files
            MODIFIED_FILES=$(git diff --staged --name-only)
            
            # Create commit message with list of modified files
            COMMIT_MSG="Add missing license headers [automated]\n\nModified files:\n"
            for file in $MODIFIED_FILES; do
              COMMIT_MSG+="- $file\n"
            done
            
            # Commit and push changes
            git commit -m "$COMMIT_MSG"
            git push
            
            echo "Successfully added license headers and pushed changes"
          else
            echo "No changes to commit"
          fi